# Generated by Django 5.2.17 on 2026-09-21 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def populate_waitlist_order(apps, schema_editor):
    Enrollment = apps.get_model('accounts', 'Enrollment')
    group_ids = Enrollment.objects.filter(status='waitlisted').values_list('group_id', flat=True).distinct()
    for group_id in group_ids:
        waiting = Enrollment.objects.filter(group_id=group_id, status='waitlisted').order_by('requested_at', 'id')
        for position, enrollment in enumerate(waiting, start=1):
            enrollment.queue_order = position
            enrollment.save(update_fields=['queue_order'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_academic_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'ordering': ['day_of_week', 'start_time', 'end_time', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['queue_order', 'requested_at', 'id']},
        ),
        migrations.AddField(
            model_name='enrollment',
            name='queue_order',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(populate_waitlist_order, migrations.RunPython.noop),
        migrations.AddField(
            model_name='group',
            name='section',
            field=models.CharField(default='A', max_length=3),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'waitlisted')), fields=('group', 'queue_order'), name='unique_waitlist_order_per_group'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('course', 'section'), name='group_section_per_course_unique'),
        ),
        migrations.AddField(
            model_name='groupschedule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='accounts.group'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='groupschedule',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='schedule_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='groupschedule',
            constraint=models.UniqueConstraint(fields=('group', 'day_of_week', 'start_time', 'end_time'), name='unique_group_schedule_block'),
        ),
    ]
